/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlm3hernandez;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import static javax.management.Query.value;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author mariohervil
 */
public class FrameStudent extends javax.swing.JFrame {

    /**
     * Creates new form FrameStudent
     */
    public FrameStudent() {

        initComponents();

        this.getContentPane().setBackground(new Color(153, 0, 0));
        initConfig();
        this.setLocationRelativeTo(this);
        curDateTime();
        labelTeacher.setVisible(false);
        comboBoxTeacher.setVisible(false);
        

        
        

    }

    private void viewTeacher() {
        comboBoxTeacher.removeAllItems();

        for (Teacher t : DataClass.ALteacher) {

            comboBoxTeacher.addItem(t.getDni());

        }

    }
    private Teacher searchTeacher(String dni){
        Teacher teacher = null;
        for (Teacher t : DataClass.ALteacher) {
            if (t.getDni().equals(dni)) {
                teacher = t;
                break;
            }
            
        }
        return teacher;
    }

    public boolean validateSTDni(Student newStudent) {
        boolean ok = true;
        for (Student s : DataClass.ALstudent) {
            if (s.getDni().equals(newStudent.getDni())) {
                ok = false;
                break;

            } else {
                ok = true;
            }

        }
        return ok;

    }

    private void initConfig() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screen.width * 50 / 100;
        int height = (int) screen.height * 85 / 100;
        this.setSize(height, width);
    }

    public final void curDateTime() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        dateTime.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAge = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelSurname = new javax.swing.JLabel();
        textSurname = new javax.swing.JTextField();
        labelDni = new javax.swing.JLabel();
        textDni = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        labelAge = new javax.swing.JLabel();
        textApproved = new javax.swing.JTextField();
        labelApproved = new javax.swing.JLabel();
        textTuition = new javax.swing.JTextField();
        labelTeacher = new javax.swing.JLabel();
        buttonCreate = new javax.swing.JButton();
        buttonGoBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dateTime = new javax.swing.JLabel();
        buttonShow = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textShow = new javax.swing.JTextArea();
        buttonDelete = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();
        labelStudents = new javax.swing.JLabel();
        labelTuition1 = new javax.swing.JLabel();
        comboBoxTeacher = new javax.swing.JComboBox<>();
        jCheckBoxTeacher = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAge.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N

        textName.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N

        labelName.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Name");

        labelSurname.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelSurname.setForeground(new java.awt.Color(255, 255, 255));
        labelSurname.setText("Surname");

        textSurname.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N

        labelDni.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelDni.setForeground(new java.awt.Color(255, 255, 255));
        labelDni.setText("DNI");

        textDni.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N

        labelEmail.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("Email");

        textEmail.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N

        labelAge.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelAge.setForeground(new java.awt.Color(255, 255, 255));
        labelAge.setText("Age");

        textApproved.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N

        labelApproved.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelApproved.setForeground(new java.awt.Color(255, 255, 255));
        labelApproved.setText("Approved");

        textTuition.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N

        labelTeacher.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelTeacher.setForeground(new java.awt.Color(255, 255, 255));
        labelTeacher.setText("Teacher");

        buttonCreate.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        buttonCreate.setText("Create");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        buttonGoBack.setText("Back");
        buttonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGoBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student");

        textDate.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        dateTime.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        dateTime.setForeground(new java.awt.Color(255, 255, 255));
        dateTime.setText("jLabel3");

        buttonShow.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        buttonShow.setText("Show students");
        buttonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowActionPerformed(evt);
            }
        });

        textShow.setColumns(20);
        textShow.setRows(5);
        jScrollPane2.setViewportView(textShow);

        buttonDelete.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        labelError.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 255, 0));

        labelStudents.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelStudents.setForeground(new java.awt.Color(255, 255, 255));

        labelTuition1.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        labelTuition1.setForeground(new java.awt.Color(255, 255, 255));
        labelTuition1.setText("Tuition");

        comboBoxTeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBoxTeacher.setText("Add Teacher");
        jCheckBoxTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonGoBack)
                .addGap(331, 331, 331)
                .addComponent(jLabel1)
                .addGap(143, 143, 143)
                .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelName)
                .addGap(77, 77, 77)
                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelSurname)
                .addGap(50, 50, 50)
                .addComponent(textSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addComponent(labelAge)
                .addGap(49, 49, 49)
                .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelDni)
                .addGap(86, 86, 86)
                .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(labelApproved)
                .addGap(4, 4, 4)
                .addComponent(textApproved, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelEmail)
                .addGap(68, 68, 68)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284)
                .addComponent(labelTuition1)
                .addGap(17, 17, 17)
                .addComponent(textTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(labelTeacher)
                .addGap(18, 18, 18)
                .addComponent(comboBoxTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(buttonShow))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(labelStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxTeacher)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonGoBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(jLabel2))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelSurname))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(textSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelAge))
                    .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labelDni))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelApproved))
                    .addComponent(textApproved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelEmail))
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelTuition1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(textTuition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTeacher))))
                .addGap(4, 4, 4)
                .addComponent(jCheckBoxTeacher)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(buttonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(labelStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed

        Student student = new Student();
        student.setTeacher(searchTeacher(comboBoxTeacher.getSelectedItem().toString()));
        student.setName(textName.getText());
        student.setSurname(textSurname.getText());
        student.setAge(Integer.parseInt(textAge.getText()));
        student.setDni(textDni.getText());
        student.setEmail(textEmail.getText());
        student.setDateAlta(textDate.getText());
        student.setAprobado(Integer.parseInt(textApproved.getText()));
        student.setEnroll(Float.parseFloat(textTuition.getText()));
        jTextArea1.setText(student.toString());

        if (validateSTDni(student) == true) {
            DataClass.ALstudent.add(student);

        } else if (validateSTDni(student) == false) {

            JOptionPane.showMessageDialog(rootPane, "That DNI already exists.", "STUDENT DNI DUPLICATION", HEIGHT);
            textDni.setText("");
            labelError.setText("DNI duplicated!");
        }

        DataClass.ALstudent.add(student);

        System.out.println("Numero de elementos(Objeto)de tipo student " + DataClass.ALstudent.size());

        //visualizar datos
        for (Student s : DataClass.ALstudent) {
            System.out.println(s);
        }

        labelStudents.setText("Number of students: " + DataClass.ALstudent.size());

    }//GEN-LAST:event_buttonCreateActionPerformed

    //valirdar la no duplicación del dni -> devuelve true/false

    private void buttonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGoBackActionPerformed
        DataClass.gotoJF(this, DataClass.jFmain);
    }//GEN-LAST:event_buttonGoBackActionPerformed

    private void buttonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowActionPerformed
        for (Student s : DataClass.ALstudent) {
            String txt = "";
            textShow.setText("Number of students:" + DataClass.ALstudent.size());
            txt += ("\n\n" + s.toString());
            textShow.setText(txt);
        }


    }//GEN-LAST:event_buttonShowActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        int yesorno = JOptionPane.showConfirmDialog(null, "Delete Student?", "Delete Student", JOptionPane.YES_NO_OPTION);
        if (yesorno == 0) {
            DataClass.ALstudent.remove(search(textDni.getText()));
        } else {
        }
        labelStudents.setText("Number of students: " + DataClass.ALstudent.size());

    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void jCheckBoxTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTeacherActionPerformed
        if (jCheckBoxTeacher.isSelected()) {
            comboBoxTeacher.removeAllItems();

            for (Teacher t : DataClass.ALteacher) {
                comboBoxTeacher.addItem(t.getDni());
            }

            comboBoxTeacher.setVisible(true);

        } else {
            comboBoxTeacher.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxTeacherActionPerformed

    public static Student search(String dni) {
        Student resultado = null;
        for (Student student : DataClass.ALstudent) {
            if (student.getDni().equals(dni)) {

                resultado = student;
                break;
            }
        }
        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreate;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonGoBack;
    private javax.swing.JButton buttonShow;
    private javax.swing.JComboBox<String> comboBoxTeacher;
    private javax.swing.JLabel dateTime;
    private javax.swing.JCheckBox jCheckBoxTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelApproved;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelStudents;
    private javax.swing.JLabel labelSurname;
    private javax.swing.JLabel labelTeacher;
    private javax.swing.JLabel labelTuition1;
    private javax.swing.JTextField textAge;
    private javax.swing.JTextField textApproved;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textName;
    private javax.swing.JTextArea textShow;
    private javax.swing.JTextField textSurname;
    private javax.swing.JTextField textTuition;
    // End of variables declaration//GEN-END:variables
}
