/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *
 */
package controlm3hernandez;

import java.awt.Color;
import java.time.LocalDateTime;
import static java.time.LocalDateTime.now;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author mariohervil
 */
public class FrameNavegar extends javax.swing.JFrame {

    /**
     * Creates new form FrameNavegar
     */
    public FrameNavegar() {
        initComponents();
        this.getContentPane().setBackground(new Color(4, 23, 40, 255));
        this.setLocationRelativeTo(this);
        DataClass.jFmain = this;
        curDateTime();
        dataEnter();

    }

    private void dataEnter() {
        // adds teachers
        Teacher teacher = new Teacher("Francisco Javier", "Castro", "12345678Z", "aa@bb.com", "01/11/2021", 983);
        Teacher t = new Teacher("Pepito", "Calleja", "32432433T", "bb@cc.com", "01/11/2021", 4534);
        Teacher t1 = new Teacher("Julián", "Pérez", "83744873X", "cc@dd.com", "01/11/2021", 3435);
        DataClass.ALteacher.add(t);
        DataClass.ALteacher.add(t1);
        DataClass.ALteacher.add(teacher);
        
        Student student = new Student("Juan Carlos", "Rodríguez", "93584934X","jc@gmail.com", "25/9/2020", 19, 1, 200);
        DataClass.ALstudent.add(student);
        Student student1 = new Student("José", "Blanco", "78327821T","jb@gmail.com", "25/9/2019", 18, 2, 500);
        DataClass.ALstudent.add(student1);
        
    }

    public final void curDateTime() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        dateTime.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameTeacher = new javax.swing.JButton();
        jFrameEmployee = new javax.swing.JButton();
        jFrameStudent = new javax.swing.JButton();
        dateTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonStats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFrameTeacher.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jFrameTeacher.setText("Create Teacher");
        jFrameTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrameTeacherActionPerformed(evt);
            }
        });

        jFrameEmployee.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jFrameEmployee.setText("Create Employee");
        jFrameEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrameEmployeeActionPerformed(evt);
            }
        });

        jFrameStudent.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jFrameStudent.setText("Create Student");
        jFrameStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrameStudentActionPerformed(evt);
            }
        });

        dateTime.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        dateTime.setForeground(new java.awt.Color(255, 255, 255));
        dateTime.setText("jLabel4");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee-removebg-preview.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students.png"))); // NOI18N

        jButtonStats.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        jButtonStats.setText("Go to stats");
        jButtonStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jFrameEmployee))
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFrameTeacher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(jFrameStudent)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jButtonStats)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dateTime)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFrameEmployee)
                                    .addComponent(jFrameTeacher)
                                    .addComponent(jFrameStudent)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jButtonStats)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFrameTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrameTeacherActionPerformed
        DataClass.gotoJF(this, DataClass.jF3);

    }//GEN-LAST:event_jFrameTeacherActionPerformed

    private void jFrameEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrameEmployeeActionPerformed
        DataClass.gotoJF(this, DataClass.jF1);


    }//GEN-LAST:event_jFrameEmployeeActionPerformed

    private void jFrameStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrameStudentActionPerformed
        DataClass.gotoJF(this, DataClass.jF2);

    }//GEN-LAST:event_jFrameStudentActionPerformed

    private void jButtonStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatsActionPerformed
        DataClass.gotoJF(this, DataClass.jF4);
    }//GEN-LAST:event_jButtonStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNavegar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNavegar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNavegar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNavegar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNavegar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateTime;
    private javax.swing.JButton jButtonStats;
    private javax.swing.JButton jFrameEmployee;
    private javax.swing.JButton jFrameStudent;
    private javax.swing.JButton jFrameTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
